# Generated by Django 3.1.5 on 2021-01-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('tag1', models.CharField(max_length=1000)),
                ('tag2', models.CharField(max_length=1000)),
                ('tag3', models.CharField(max_length=1000)),
                ('tag4', models.CharField(max_length=1000)),
                ('tag5', models.CharField(max_length=1000)),
                ('tag6', models.CharField(max_length=1000)),
                ('tag7', models.CharField(max_length=1000)),
                ('tag8', models.CharField(max_length=1000)),
                ('tag9', models.CharField(max_length=1000)),
                ('tag10', models.CharField(max_length=1000)),
            ],
        ),
    ]
